# Generated by Django 3.2 on 2022-06-07 17:49

from django.db import migrations


def migrate_model2_data(apps, schema_editor):
    """
    model2データをマイグレート
    """
    old_model2_model = apps.get_model('app1', 'Model2')
    new_model2_model = apps.get_model('app2', 'Model2')
    for old_model2 in old_model2_model.objects.all():
        new_model2_model.objects.create(
            attr1=old_model2.attr1,
            attr2=old_model2.attr2
        )


def rollback_model2_data(apps, schema_editor):
    """
    model2データをロールバック
    """
    old_model2_model = apps.get_model('app1', 'Model2')
    new_model2_model = apps.get_model('app2', 'Model2')
    for new_model2 in new_model2_model.objects.all():
        old_model2_model.objects.create(
            attr1=new_model2.attr1,
            attr2=new_model2.attr2
        )
    # データ移行が完了したら移行元データを削除する
    new_model2_model.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        # app2のスキーママイグレーションより後に実行する
        ('app2', '0001_initial')
    ]

    operations = [
        migrations.RunPython(
            code=migrate_model2_data,
            reverse_code=rollback_model2_data
        )
    ]
